// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTask(arg1) {
  return window['go']['main']['App']['CancelTask'](arg1);
}

export function ChooseFile(arg1) {
  return window['go']['main']['App']['ChooseFile'](arg1);
}

export function ChooseFolder(arg1) {
  return window['go']['main']['App']['ChooseFolder'](arg1);
}

export function ConfigPath() {
  return window['go']['main']['App']['ConfigPath']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function PreviewFile(arg1, arg2) {
  return window['go']['main']['App']['PreviewFile'](arg1, arg2);
}

export function PreviewFolder(arg1, arg2) {
  return window['go']['main']['App']['PreviewFolder'](arg1, arg2);
}

export function RespondFileBlocked(arg1, arg2) {
  return window['go']['main']['App']['RespondFileBlocked'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartExtract(arg1) {
  return window['go']['main']['App']['StartExtract'](arg1);
}

export function StartSplit(arg1) {
  return window['go']['main']['App']['StartSplit'](arg1);
}
