// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function CancelTask(arg1:string):Promise<boolean>;

export function ChooseFile(arg1:string):Promise<string>;

export function ChooseFolder(arg1:string):Promise<string>;

export function ConfigPath():Promise<string>;

export function LoadConfig():Promise<string>;

export function OpenPath(arg1:string):Promise<void>;

export function PreviewFile(arg1:string,arg2:number):Promise<service.FilePreview>;

export function PreviewFolder(arg1:string,arg2:number):Promise<service.HeaderPreview>;

export function RespondFileBlocked(arg1:string,arg2:string):Promise<boolean>;

export function SaveConfig(arg1:string):Promise<void>;

export function StartExtract(arg1:service.ExtractRequest):Promise<service.TaskHandle>;

export function StartSplit(arg1:service.SplitRequest):Promise<service.TaskHandle>;
